/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_aggregate_g1_flat: (a: number, b: number) => [number, number, number, number];
export const wasm_aggregate_g1_signed: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasm_aggregate_g2_flat: (a: number, b: number) => [number, number, number, number];
export const wasm_aggregate_g2_signed: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasm_decapsulate_epoch_key: (a: any) => [number, number, number, number];
export const wasm_decapsulate_epoch_key_flat: (a: any) => [number, number, number, number];
export const wasm_derive_admin_secret: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_derive_room_public_key: (a: any) => [number, number, number, number];
export const wasm_encapsulate_epoch_key: (a: any) => [number, number, number];
export const wasm_encapsulate_epoch_key_flat: (a: any) => [number, number, number];
export const wasm_extract_user_secret: (a: any, b: number, c: number) => [number, number, number];
export const wasm_extract_user_secret_from_g1_power: (a: any, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasm_params_root: (a: any) => [number, number, number, number];
export const wasm_prefix_g1_powers: (a: any) => [number, number, number];
export const wasm_prefix_g2_powers: (a: any) => [number, number, number];
export const wasm_setup_public_params: (a: any) => [number, number, number];
export const xpkt_bgw_backend_status: () => [number, number];
export const xpkt_bgw_curve_id: () => [number, number];
export const xpkt_bgw_scheme_id: () => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
